# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-30 17:12
from __future__ import unicode_literals

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=128)),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from=models.CharField(max_length=128))),
                ('start', models.DateField()),
                ('end', models.DateField()),
                ('details', models.TextField(max_length=2000)),
                ('image', models.ImageField(upload_to=b'')),
            ],
            options={
                'ordering': ['start'],
            },
        ),
    ]
