# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-04 19:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0002_auto_20170802_0557'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='slug',
            new_name='item_slug',
        ),
    ]
