# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-08-07 17:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clothing', '0003_auto_20170804_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='item_slug',
            new_name='slug',
        ),
    ]
